/** Mock do parque — apenas nomes e specs públicas. Sem credenciais, hosts reais ou AnyDesk. */
export type MockLabMachine = {
  name: string
  hasGpu: boolean
  cpuModel: string
  gpuModel: string | null
  /** RAM wire GB×10 */
  totalRamGb: number
  /** VRAM wire GB×10 */
  totalVramGb: number | null
  /** Sem SSH exposto no seed (AnyDesk ou acesso interno). */
  anyDeskOnly: boolean
  disksGb: number[]
}

export const ANYDESK_DESCRIPTION = 'Máquinas acessível apenas por AnyDesk'

export const MOCK_LAB_MACHINES: MockLabMachine[] = [
  {
    name: 'Euler',
    hasGpu: true,
    cpuModel: 'Intel Core i9-14900F 3.6 GHz',
    gpuModel: 'NVIDIA RTX A6000',
    totalRamGb: 960,
    totalVramGb: 480,
    anyDeskOnly: false,
    disksGb: [4000, 1000],
  },
  {
    name: 'Dijkstra',
    hasGpu: true,
    cpuModel: 'Intel Core i9-10900 2.80 GHz',
    gpuModel: 'NVIDIA RTX 4070 Ti',
    totalRamGb: 320,
    totalVramGb: 120,
    anyDeskOnly: true,
    disksGb: [1000],
  },
  {
    name: 'GaciG1',
    hasGpu: false,
    cpuModel: 'Intel Xeon E5-2640 v3 2.60 GHz',
    gpuModel: null,
    totalRamGb: 320,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [2000],
  },
  {
    name: 'GaciG2',
    hasGpu: false,
    cpuModel: 'Intel Xeon E5-2650 v4 2.20 GHz',
    gpuModel: null,
    totalRamGb: 480,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [2000, 20],
  },
  {
    name: 'GaciG3',
    hasGpu: false,
    cpuModel: 'Intel Xeon E5-2650 v4 2.20 GHz',
    gpuModel: null,
    totalRamGb: 480,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [2000],
  },
  {
    name: 'GaciG4',
    hasGpu: false,
    cpuModel: 'Intel Xeon E5-2650 v4 2.20 GHz (dual)',
    gpuModel: null,
    totalRamGb: 960,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [2000],
  },
  {
    name: 'GaciG5',
    hasGpu: false,
    cpuModel: 'Intel Xeon Gold 5118 2.30 GHz',
    gpuModel: null,
    totalRamGb: 560,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [2000],
  },
  {
    name: 'GaciG6',
    hasGpu: false,
    cpuModel: 'Intel Xeon Gold 5120 2.20 GHz',
    gpuModel: null,
    totalRamGb: 1280,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [2000, 960],
  },
  {
    name: 'GaciG7',
    hasGpu: false,
    cpuModel: 'Intel Xeon Silver 4314 2.40 GHz',
    gpuModel: null,
    totalRamGb: 960,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [480],
  },
  {
    name: 'GaciG8',
    hasGpu: false,
    cpuModel: 'Intel Xeon Silver 4316 (Dell R450)',
    gpuModel: null,
    totalRamGb: 1280,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [960, 4000],
  },
  {
    name: 'GaciG9',
    hasGpu: false,
    cpuModel: 'Intel Xeon Silver 4309Y 2.30 GHz',
    gpuModel: null,
    totalRamGb: 1280,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [4000],
  },
  {
    name: 'GaciS1',
    hasGpu: false,
    cpuModel: 'Intel Xeon E5645 2.4 GHz',
    gpuModel: null,
    totalRamGb: 240,
    totalVramGb: null,
    anyDeskOnly: false,
    disksGb: [2000, 300],
  },
  {
    name: 'Arendt',
    hasGpu: true,
    cpuModel: 'Intel Core i7-11700 2.5 GHz',
    gpuModel: 'NVIDIA RTX 4090 D',
    totalRamGb: 480,
    totalVramGb: 240,
    anyDeskOnly: false,
    disksGb: [480, 2000],
  },
  {
    name: 'Chomsky',
    hasGpu: true,
    cpuModel: 'Intel Core i7-11700 2.5 GHz',
    gpuModel: 'NVIDIA RTX 3080',
    totalRamGb: 320,
    totalVramGb: 100,
    anyDeskOnly: true,
    disksGb: [1000],
  },
  {
    name: 'Confúcio',
    hasGpu: true,
    cpuModel: 'Intel Core i7-10700F 2.9 GHz',
    gpuModel: 'NVIDIA GeForce RTX 3060',
    totalRamGb: 320,
    totalVramGb: 120,
    anyDeskOnly: true,
    disksGb: [480],
  },
  {
    name: 'Hinton',
    hasGpu: true,
    cpuModel: 'Intel Core i7-14700F',
    gpuModel: 'NVIDIA RTX 4090',
    totalRamGb: 160,
    totalVramGb: 240,
    anyDeskOnly: true,
    disksGb: [500],
  },
  {
    name: 'Moore',
    hasGpu: true,
    cpuModel: 'Intel Core i9-9900KF 3.6 GHz',
    gpuModel: 'NVIDIA TITAN',
    totalRamGb: 320,
    totalVramGb: 120,
    anyDeskOnly: true,
    disksGb: [1000, 5000],
  },
  {
    name: 'Sócrates',
    hasGpu: true,
    cpuModel: 'AMD Ryzen 7 5700X 3.4 GHz',
    gpuModel: 'NVIDIA GeForce RTX 3070',
    totalRamGb: 320,
    totalVramGb: 80,
    anyDeskOnly: true,
    disksGb: [480],
  },
  {
    name: 'Darwin',
    hasGpu: true,
    cpuModel: 'Intel Core i7-10700F 2.9 GHz',
    gpuModel: 'NVIDIA GeForce RTX 3080',
    totalRamGb: 480,
    totalVramGb: 100,
    anyDeskOnly: true,
    disksGb: [480],
  },
]
